### PR TITLE
Minor deletions

### PR DESCRIPTION
**Pull request by djnavarro**
Hi Jess,

This pull request doesn't do anything major: it looks like you have a few system files that must have been committed to the repository before you updated your `.gitignore` file. All this does is delete those files: there are two DS_Store files and several empty files that start with a `._` prefix that I *think* serve no purpose? Assuming that's correct, all this will do is sweep those files out of your repository.

As always, please ignore if I've mistaken something!

Best
Dani

### CODE REVIEW

**Comment by jessica-c-lee** [comment]
Thanks Dani, yep those files are useless.

**Comment by djnavarro** [comment]
Did you want to merge this into your master branch? (i.e., if you don't want to be bothered deleting the files yourself you can just merge my pull request if you like).

Apologies if I'm telling you something you already know :smile:

**Comment by jessica-c-lee** [comment]
Apologies - I swear I know what I'm doing...

**Comment by djnavarro** [comment]
Awesome! No apologies necessary :slightly_smiling_face:. Trust me, I've gone through the same process and have had to rely on other people who have kindly helped me navigate the treachery of git. It's very much a "pay it forward" situation!

**Pull request merged**
